/**
 * @pseudopilot/language-core
 *
 * Deterministic Cambridge pseudocode language pipeline.
 * Lexer + recursive-descent / Pratt parser → AST.
 */

export const PACKAGE_NAME = '@pseudopilot/language-core' as const;
export const PACKAGE_VERSION = '1.0.0-beta.0' as const;

export {
  parse,
  DEFAULT_MAX_SOURCE_CHARS,
  ABSOLUTE_MAX_SOURCE_CHARS,
  DEFAULT_MAX_BLOCK_NESTING,
  P_NESTING_TOO_DEEP,
  type ParseResult,
  type ParseOptions,
} from './parse.js';
export { lex, type LexResult, type LexOptions } from './lexer/lexer.js';
export type {
  Program,
  Statement,
  Expression,
  AssignmentStatement,
  InputStatement,
  OutputStatement,
  IfStatement,
  CaseStatement,
  CaseArm,
  CaseLabel,
  WhileStatement,
  RepeatStatement,
  ForStatement,
  ElseIfClause,
  DeclareStatement,
  ConstantStatement,
  ProcedureDeclaration,
  FunctionDeclaration,
  CallStatement,
  ReturnStatement,
  OpenFileStatement,
  ReadFileStatement,
  WriteFileStatement,
  CloseFileStatement,
  SeekStatement,
  GetRecordStatement,
  PutRecordStatement,
  CallExpression,
  IndexExpression,
  EofExpression,
  MemberExpression,
  SuperExpression,
  NewExpression,
  MethodCallExpression,
  ArrayType,
  ArrayDimension,
  TypeReference,
  NamedType,
  SimpleType,
  AssignTarget,
  FileMode,
  Parameter,
  ParameterMode,
  TypeName,
  TypeNameKind,
  TypeDeclaration,
  EnumTypeDeclaration,
  PointerTypeDeclaration,
  SetTypeDeclaration,
  DefineStatement,
  Visibility,
  ClassPropertyDeclaration,
  ClassProcedureDeclaration,
  ClassFunctionDeclaration,
  ClassMember,
  ClassDeclaration,
  ExpressionStatement,
  Identifier,
  BinaryExpression,
  UnaryExpression,
  GroupingExpression,
  AddressOfExpression,
  DerefExpression,
  IntegerLiteral,
  RealLiteral,
  StringLiteral,
  CharLiteral,
  BooleanLiteral,
  DateLiteral,
  BinaryOperator,
  UnaryOperator,
  AstNode,
} from './ast/nodes.js';
export { TokenKind, type Token, isTypeToken, isFileModeToken } from './lexer/token.js';
export {
  CORE_BUILTINS,
  lookupBuiltin,
  isBuiltinName,
  allBuiltinNames,
  type BuiltinSpec,
  type BuiltinParamSpec,
} from './builtins/registry.js';
export type {
  Diagnostic,
  DiagnosticSeverity,
  Position,
  SourceSpan,
} from './diagnostics.js';
